from Bio.Seq import Seq
from Bio.Alphabet import generic_dna
from Bio.Data import CodonTable


gene = Seq("GGAGTACAATGATTCAGAACCCTGGGTGAGTGGAAGCCCCGGCAGATCGACAACCCAGAT" +
           "TACAAGGGCACTTGGATCCACCCAGAAATTGACAACCCCGAGTATTCTCCCGATCCCAGT" +
           "ATCTATGCCTATGATAGACTTCCTGCCACCCAAGAAGATAAAGGATCCTGATGCTTCAAA" +
           "ACCGGAAGACTGGGATGAGCGGGCCAAGATCGATGATCCCACAGACTCCAAGCCTGAGGA" +
           "CTGGGACAAGCCCGAGCATATCCCTGACCCTGATGCTAAGAAGCCCGAGGACTGGGATGA" +
           "AGAGATGGACGGAGAGTGGGAACCCCCAACTTTGGCGTGCTGGGCCTGGACCTCTGGCAG" +
           "GTCAAGTCTGGCACCATCTTTGACAACTTCCTCATCACCAACGATGAGGCATACGCTGAG" +
           "GAGTTTGGCAACGAGACGTGGGGCGTAACAAAGGCAGCAGAGAAACAAATGAAGGACAAA" +
           "CAGGACGAGGAGCAGAGGCTTAAGGAGGAGGAAGAAGACAAGAAACGCAAAGAGGAGGAG" +
           "GAGGCAGAGGACAAGGAGGATGAA", generic_dna)

print('DNA  = ' + gene)
print('RNAm = ' + gene.transcribe())

g = gene.translate(table='Standard')
print('Prot = ' + g)


standard_table = CodonTable.unambiguous_dna_by_name["Standard"]
print(standard_table)
standard_table
